### PR TITLE
lib: tidy up with the RustFMT tool

### PR DESCRIPTION
**Pull request by shymega**
This commit has had RustFMT run over the existing code, and format it
accordingly.

If you don't want to accept this PR, that's fine, but I highly recommend RustFMT- it does a good job of making the code look cleaner.

Also, FWIW, I tested this crate, and it seems to work as expected. There are no breakages, as far as I can see.

### CODE REVIEW

**Comment by shymega** [comment]
Famous last words, it seems. It doesn't fail on my Nightly toolchain, but I might be out of date.. :-1:

**Comment by shymega** [comment]
Updating toolchain, once I find the bug, I'll push more commits.

**Comment by shymega** [comment]
Did a bit more poking around- the unit tests *are* failing, but that is because the env vars aren't in place yet. With Travis-CI, you can create encrypted hashes of data, so you /could/ commit that API key, plus the user, and this PR should pass! cc/ @RoxasShadow

**Comment by RoxasShadow** [comment]
Hey @shymega, thanks for this.

Honestly I like a lot what RustFMT does and I think that in general it's an amazing tool, but I prefer to keep things like the alignment of operators, the lack of comma for the very last field of a struct and the split of the content of an array to multiple line as they are now.

I will fix the tests, merge this PR and then do a some little cleaning on the RustFMT's work.

**Comment by RoxasShadow** [comment]
The keys encrypted by travis are not available for PRs as far as I know as they're bounded to the original repository. I added new keys to travis but it is still failing – I will check this on master for this time.

**Comment by RoxasShadow** [comment]
I actually started reverting most of the things, so I decided at the end to revert the changes. I'm very sorry, but I have my own coding style that doesn't match a lot to the RustFMT's 😞 

Anyway, tests passed now. There must be something weird on travis that doesn not keep the ENV vars on builds coming from different repos...

**Comment by shymega** [comment]
Understood. No matter. When/if I submit code to this repository, I'll make sure to turn off RustFMT to conform to your coding style. 

FWIW, RustFMT can be configured with a `rustfmt.toml` file in the root directory- not sure if that would help?

**Pull request merged**
